name: SlicerStaffCommands
version: '${project.version}'
main: com.malcolmjh.slicerstaffcommands.SlicerStaffCommands
api-version: '1.20'
commands:
  hologram:
    usage: /<command> <color ID><text>
    description: Makes a invisable armor stand with the name you gave it and the color if the color ID you provided.
    permission-message: You need to be a staff member to use this command
    permission: slicer.staff.holo
  invsee:
    usage: /<command> <username>
    description: Lets you see in someones inventory.
    permission-message: You need to be a staff member to use this command
    permission: slicer.staff.invsee
  notice:
    usage: /<command> <username>
    permission-message: Unknown command. Type "/help" for help.
    permission: slicer.staff.notice
  setspawn:
    description: Set the spawn point
    permission: slicer.staff.setspawn
  spawn:
    description: Teleport a player at the spawn location
    permission: slicer.spawn.spawn
